# Generated by Django 6.0.4 on 2026-04-26 09:46

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_off_duty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_sleeper', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_driving', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_on_duty_nd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('remarks', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'daily_logs',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('address_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('raw_address', models.TextField()),
                ('display_name', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geocode_cache',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.TextField()),
                ('pickup_location', models.TextField()),
                ('dropoff_location', models.TextField()),
                ('cycle_hours_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('total_miles', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_duration_hrs', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('eta', models.DateTimeField(null=True)),
                ('route_geojson', models.JSONField(null=True)),
                ('result_json', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('SLEEPER_BERTH', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON_DUTY_NOT_DRIVING', 'On Duty (Not Driving)')], max_length=24)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hrs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_text', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'trip_segments',
                'ordering': ['sequence'],
            },
        ),
    ]
